### ISSUE TITLE
[Note to self] Bug Fix

### ISSUE THREAD

**Issue by IchimakiKasura** [IchimakiKasura/HoyoLauncher#2]
**Version**: 1.8.804.5

**Problem**:
 - game pre-install button and the launch button becomes enabled when clicking the confirm on the settings while downloading.
![image](https://github.com/IchimakiKasura/CeeleLauncher/assets/80595346/908db2c1-f1a5-44e9-a113-cf1890928fb6)

**Comment by unbeleeveeable** [comment]
getting a config error "Object reference not set to an instance of an object."

**Comment by IchimakiKasura** [comment]
> getting a config error "Object reference not set to an instance of an object."

Can you please elaborate the question and provide some images so I can see what's happening?
